### PR TITLE
adding standardized PGN for each opening

### PR DESCRIPTION
**Pull request by jecker7**
Let me know if you need any changes or validation on this. The PGN added is a bit redundant with the game notation already included, but thought it would make things easier for PGN parsing of the openings.

### CODE REVIEW

**Comment by niklasf** [comment]
Thanks for the patch. I realize the FEN could already be generated from `moves`, but I don't like adding further redundant information.

**Comment by jecker7** [comment]
What's the reasoning for including moves instead of PGN?

**Comment by niklasf** [comment]
Oh, that's a weak preference. I'd accept a PR that *replaces* it.

**Comment by niklasf** [comment]
Done this now. The files are now edited as PGN and all columns with redundant information are generated.

**Pull request closed without merging**
